[package]
name = "startpage"
version = "1.0.0"
edition = "2021"

[dependencies]
wee_alloc = "0.4"
sycamore = "0.8"
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
